version: '3.8'

services:
  db-unidade-alfa:
    container_name: db-unidade-alfa
    image: postgres:9.6
    networks:
      - borelanjo-network
    restart: always
    hostname: db-unidade-alfa
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: unidade-alfa
      POSTGRES_USER: unidade-alfa
      POSTGRES_PASSWORD: unidade-alfa
      PGDATA: /tmp
    volumes:
      - ./docker/postgres/data-unidade-alfa:/var/lib/postgresql/data
  db-unidade-beta:
    container_name: db-unidade-beta
    image: postgres:9.6
    networks:
      - borelanjo-network
    restart: always
    hostname: db-unidade-beta
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: unidade-beta
      POSTGRES_USER: unidade-beta
      POSTGRES_PASSWORD: unidade-beta
      PGDATA: /tmp
    volumes:
      - ./docker/postgres/data-unidade-beta:/var/lib/postgresql/data

  activemq-service:
    image: rmohr/activemq
    networks:
      - borelanjo-network
    ports:
      - 8161:8161
      - 61616:61616

  eureka-service:
    image: 'borelanjo/eureka:latest'
    networks:
      - borelanjo-network
    ports:
      - "8761:8761"

  gateway-service:
    image: 'borelanjo/gateway-service:latest'
    networks:
      - borelanjo-network
    ports:
      - "8080:8080"
    depends_on:
      - eureka-service
    environment:
      APP_URL: gateway-service
      EUREKA_DEFAULT_ZONE: 'http://eureka-service:8761/eureka'

  paciente-alfa-producer-service:
    image: 'borelanjo/paciente-producer-service:latest'
    networks:
      - borelanjo-network
    depends_on:
      - eureka-service
    environment:
      APP_URL: paciente-alfa-producer-service
      EUREKA_DEFAULT_ZONE: 'http://eureka-service:8761/eureka'
      ACTIVEMQ_BROKER_URL: 'tcp://activemq-service:61616'
  paciente-beta-producer-service:
    image: 'borelanjo/paciente-producer-service:latest'
    networks:
      - borelanjo-network
    depends_on:
      - eureka-service
    environment:
      APP_URL: paciente-beta-producer-service
      EUREKA_DEFAULT_ZONE: 'http://eureka-service:8761/eureka'
      ACTIVEMQ_BROKER_URL: 'tcp://activemq-service:61616'

  paciente-alfa-consumer-service:
    image: 'borelanjo/paciente-consumer-service:latest'
    networks:
      - borelanjo-network
    depends_on:
      - eureka-service
    environment:
      EUREKA_DEFAULT_ZONE: 'http://eureka-service:8761/eureka'
      ACTIVEMQ_BROKER_URL: 'tcp://activemq-service:61616'
      DB_UNIDADE_URL: 'jdbc:postgresql://db-unidade-alfa:5432/unidade-alfa?createDatabaseIfNotExist=true'
      DB_UNIDADE_USERNAME: 'unidade-alfa'
      DB_UNIDADE_PASSWORD: 'unidade-alfa'
  paciente-beta-consumer-service:
    image: 'borelanjo/paciente-consumer-service:latest'
    networks:
      - borelanjo-network
    depends_on:
      - eureka-service
    environment:
      EUREKA_DEFAULT_ZONE: 'http://eureka-service:8761/eureka'
      ACTIVEMQ_BROKER_URL: 'tcp://activemq-service:61616'
      DB_UNIDADE_URL: 'jdbc:postgresql://db-unidade-beta:5432/unidade-beta?createDatabaseIfNotExist=true'
      DB_UNIDADE_USERNAME: 'unidade-beta'
      DB_UNIDADE_PASSWORD: 'unidade-beta'

#############################################################
######################### NETWORK ###########################
#############################################################
networks:
  borelanjo-network:
    driver: "bridge"