eureka:
  instance:
    hostname: ${APP_URL:localhost}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761}
server:
  port: 8080
spring:
  application:
    name: paciente-gateway-service
  cloud:
    gateway:
      routes:
        - id: pacientes
          uri: lb://paciente-producer-service
          predicates:
            - Path=/api/pacientes/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
