eureka:
  instance:
    hostname: ${APP_URL:localhost}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761}
server:
  port: 8080
spring:
  application:
    name: paciente-consumer-service
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
    pool:
      enabled: ${ACTIVEMQ_POOL_ENABLED:true}
      max-connections: ${ACTIVEMQ_POOL_CONNECTIONS:50}
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_UNIDADE_URL:jdbc:postgresql://localhost:5432/paciente-consumer?createDatabaseIfNotExist=true}
    username: ${DB_UNIDADE_USERNAME:job1}
    password: ${DB_UNIDADE_PASSWORD:job1}
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
