eureka:
  instance:
    hostname: ${APP_URL:localhost}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761}
server:
  port: 8080
spring:
  application:
    name: paciente-consumer-service
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
    pool:
      enabled: ${ACTIVEMQ_POOL_ENABLED:true}
      max-connections: ${ACTIVEMQ_POOL_CONNECTIONS:50}
